# Generated by Django 4.1.6 on 2023-05-22 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='course',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='dob',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
