# Generated by Django 4.1.6 on 2023-05-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_signup_course_alter_signup_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='rno',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
