# Generated by Django 4.1.6 on 2023-05-22 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_signup_rno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='imaage',
            new_name='image',
        ),
    ]
