# Generated by Django 4.1.6 on 2023-05-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_rename_imaage_attendance_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='image',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
