# Generated by Django 4.1.6 on 2023-05-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_alter_attendance_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='course',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='date',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='rollno',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
