# Generated by Django 4.1.6 on 2023-05-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_attendance_course_attendance_date_attendance_rollno'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='email',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
