# Generated by Django 4.1.6 on 2023-05-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_attendance_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='image',
            field=models.CharField(max_length=536170, null=True),
        ),
    ]
