# Generated by Django 4.1.6 on 2023-05-23 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
